// import type { Metadata } from 'next';
// // import "./globals.css";
// // import "/public/assets/css/bootstrap.min.css";
// import 'bootstrap/dist/css/bootstrap.min.css';

// import '/public/assets/css/demo36.css';
// import '/public/assets/vendor/fontawesome-free/css/all.min.css';
// import TopNotice from '@/layouts/TopNotice';
// import Header from '@/layouts/Header';
// import Footer from '@/layouts/Footer';
// import MobileMenu from '@/layouts/MobileMenu';
// import { Poppins } from 'next/font/google';

// const poppins = Poppins({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-poppins',
//   weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
//   fallback: ['sans-serif'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`loaded ${poppins.className}`}>
//         <div className="page-wrapper">
//           <TopNotice />
//           <Header />
//           <main className="main">
//             {children}
//             <div className="mb-xl-4 mb-0" />
//             {/* margin */}
//           </main>
//           {/* End .main */}
//           <Footer />
//         </div>

//         <MobileMenu menuActive={menuActive} setMenuActive={setMenuActive} />

//         <a id="scroll-top" href="#top" title="Top" role="button">
//           <i className="icon-angle-up" />
//         </a>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from 'next';
// import "./globals.css";
// import "/public/assets/css/bootstrap.min.css";
import 'bootstrap/dist/css/bootstrap.min.css';

import '/public/assets/css/demo36.css';
import '/public/assets/vendor/fontawesome-free/css/all.min.css';
import TopNotice from '@/layouts/TopNotice';
import Header from '@/layouts/Header';
import Footer from '@/layouts/Footer';

import { Poppins, Open_Sans, Oswald } from 'next/font/google';
import ScrollTop from './(home)/components/ScrollTop';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700', '800'],
});

// const openSans = Open_Sans({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-open-sans',
//   weight: ['300', '400', '600', '700', '800'],
//   style: ['normal', 'italic'],
// });

// const oswald = Oswald({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-oswald',
//   weight: ['300', '400', '500', '600', '700'],
// });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <style>
          {`:root {
            --font-poppins: ${poppins.variable};
            --font-open-sans: ${openSans.variable};
            --font-oswald: ${oswald.variable};
          }`}
        </style>
      </head> */}
      <body className={`loaded ${poppins.className}`}>
        <div className="page-wrapper">
          <TopNotice />
          <Header /> {/* Pasamos la lógica del menú al Header */}
          <main className="main">
            {children}
            <div className="mb-xl-4 mb-0" />
            {/* margin */}
          </main>
          <Footer />
        </div>

        {/* Mobile Menu gestionado en los Client Components */}
        {/* <MobileMenu /> */}

        {/* <a id="scroll-top" href="#top" title="Top" role="button">
          <i className="icon-angle-up" />
        </a> */}
        <ScrollTop />
      </body>
    </html>
  );
}
