// import type { Metadata } from 'next';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import Breadcrumb from '@/app/components/BreadCrump';
// import '/public/assets/css/demo36.css';
// import '/public/assets/vendor/fontawesome-free/css/all.min.css';
// import '/public/assets/vendor/simple-line-icons/css/simple-line-icons.min.css';
// import TopNotice from '@/layouts/TopNotice';
// import Header from '@/layouts/Header';
// import Footer from '@/layouts/Footer';
// import { UserProvider } from '@/context/UserContext'; // Importa el contexto de usuario

// import { Poppins } from 'next/font/google';
// import ScrollTop from './(home)/components/ScrollTop';

// const poppins = Poppins({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-poppins',
//   weight: ['300', '400', '500', '600', '700', '800'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`loaded ${poppins.className}`}>
//         <UserProvider>
//           {/* Envolvemos toda la aplicación con el contexto */}
//           <div className="page-wrapper">
//             <TopNotice />
//             <Header />
//             <main className="main">
//               <Breadcrumb />
//               {children}
//             </main>
//             <Footer />
//           </div>
//           <ScrollTop />
//         </UserProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.min.css';
import Breadcrumb from '@/app/components/BreadCrump';
import '/public/assets/css/demo36.css';
import '/public/assets/vendor/fontawesome-free/css/all.min.css';
import '/public/assets/vendor/simple-line-icons/css/simple-line-icons.min.css';
import TopNotice from '@/layouts/TopNotice';
import Header from '@/layouts/Header';
import Footer from '@/layouts/Footer';
import { UserProvider } from '@/context/UserContext'; // Importa el contexto de usuario
import { CartProvider } from '@/context/CartContext'; // Importa el contexto del carrito

import { Poppins } from 'next/font/google';
import ScrollTop from './(home)/components/ScrollTop';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`loaded ${poppins.className}`}>
        <UserProvider>
          <CartProvider>
            <div className="page-wrapper">
              <TopNotice />
              <Header />
              <main className="main">
                <Breadcrumb />
                {children}
              </main>
              <Footer />
            </div>
            <ScrollTop />
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
